### ISSUE TITLE
Conventies opstellen

### ISSUE THREAD

**Issue by TygoWolven** [fdnd-agency/fdnd#20]
Wij gaan bespreken binnen het team welke afspraken wij gaan hanteren tijdens dit project. Verder stellen wij conventies op om te bepalen welke communicatie wij gebruiken, maar ook denken we hierbij aan onze manier van coderen.

**Comment by TygoWolven** [comment]
## Code Conventies

### Inspringen
Inspringen doen we met een enkele TAB.

````HTML
<ul>
    <li>
        <img src="" alt="">
    </li>
</ul>
````

### Witruimte
Wij gebruiken bij aparte componenten 1 enter als witruimte.

````HTML
<h1>Hallo Wereld!</h1>

<ul>
    <li>
        <img src="" alt="">
    </li>
</ul>
````

### Spatiegebruik
Als er gebruik gemaakt wordt van een dubbele punt in bijvoorbeeld CSS, dan volgt hier een spatie tussen.

````CSS
/* Zo doen we het dus! */
width: 10em;

/* En niet zo... */
width:10em;
````

### Kleurcodes
Bij het gebruik van kleuren gebruiken wij alleen HEX kleurcodes, en niet de standaard CSS kleuren.

````CSS
/* Op deze manier gebruiken wij de kleurcode */
color: #FF0000;

/* En dus niet op deze manier... */
color: red;
````

### Comments
Mocht je complexe code hebben geschreven, zet hier dan een comment bij waarin dit wordt uitgelegd.

````HTML
/* Om tekst op de pagina te tonen maak ik gebruik van een paragraaf */
<p>Ik ben hele complexe code!</p>
````

## Github Desktop Conventies

### Commit Messages
Schrijf zodra je code gaat pushen, een beschrijvende commit message waaruit duidelijk is wat je hebt gedaan.

**Comment by KaanKalmi** [comment]
Refereer naar: https://github.com/fdnd-agency/.github/wiki/Conventies
