### ISSUE TITLE
Taak: Redesign de header van FDND

### ISSUE THREAD

**Issue by lisavanmansom** [fdnd-agency/fdnd#22]
![Image](https://github.com/user-attachments/assets/49f6955a-6301-48c2-bd3e-b4716ec3c2a5)

### Prototype 1
Before:

![Image](https://github.com/user-attachments/assets/08b6a728-90a6-4532-99e1-f3565f31584a)

After:

![Image](https://github.com/user-attachments/assets/28104551-3256-44be-9967-219ad8df3f3c)

**Comment by lisavanmansom** [comment]
### Design critique

**Tip:**
1. Meer witruimte gebruiken

**Comment by Anna-Kyra** [comment]
**Design critique:**
Tip: 
1. Met de after is de tekst uitlijning overal anders. Daardoor moeten je ogen de teletijd zoeken waar die moet beginnen met lezen

**Comment by Einanas** [comment]
##Design Critique

Tips:

1. De 'after' prototype voelt leeg met hoe het content is geplaatst in het midden (maar is ook logisch omdat de rest er nog niet bij zit)

Tops:

1. De 'after' header geeft meteen een frisse look, het werd eens tijd dat het een ander look kreeg.

**Comment by KaanKalmi** [comment]
Is dit beter? (Desktop-Tablet-Smartphone)

![Image](https://github.com/user-attachments/assets/16d35f67-ee8c-46d1-ad1e-e6b300478b17)

![Image](https://github.com/user-attachments/assets/dcf220af-bad5-4d64-882f-40029c852b6e)

![Image](https://github.com/user-attachments/assets/b7b80688-7a54-4f2a-8e80-e195b3bd6e3e)
